var quotes = [
"The best way to predict the future is to invent it. – Alan Kay",
"You miss 100% of the shots you don’t take. – Wayne Gretzky",
"I have not failed. I've just found 10,000 ways that won't work. – Thomas Edison",
"Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
"In the end, we will remember not the words of our enemies, but the silence of our friends. – Martin Luther King Jr.",
"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. – Ralph Waldo Emerson",
"Life is what happens when you're busy making other plans. – John Lennon",
"The only way to do great work is to love what you do. – Steve Jobs",
"Whether you think you can or you think you can’t, you’re right. – Henry Ford",
"Believe you can and you're halfway there. – Theodore Roosevelt",
"Act as if what you do makes a difference. It does. – William James",
"Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
"Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
"Everything you’ve ever wanted is on the other side of fear. – George Addair",
"The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
"Do not wait to strike till the iron is hot, but make it hot by striking. – William Butler Yeats",
"Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
"It does not matter how slowly you go as long as you do not stop. – Confucius",
"Life is short, and it is up to you to make it sweet. – Sarah Louise Delany",
"The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
"Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
"You only live once, but if you do it right, once is enough. – Mae West",
"Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. – Albert Schweitzer",
"Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
"The best revenge is massive success. – Frank Sinatra",
"Do not wait to strike till the iron is hot, but make it hot by striking. – William Butler Yeats",
"The only impossible journey is the one you never begin. – Tony Robbins",
"Start where you are. Use what you have. Do what you can. – Arthur Ashe",
"The mind is everything. What you think you become. – Buddha",
"Success is getting what you want, happiness is wanting what you get. – W.P. Kinsella",
"You do not find the happy life. You make it. – Camilla E. Kimball",
"Life isn’t about waiting for the storm to pass; it’s about learning how to dance in the rain. – Vivian Greene",
"You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
"Everything you can imagine is real. – Pablo Picasso",
"Opportunities don't happen. You create them. – Chris Grosser",
"Don't be afraid to give up the good to go for the great. – John D. Rockefeller",
"Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
"Your time is limited, don't waste it living someone else's life. – Steve Jobs",
"Don't count the days, make the days count. – Muhammad Ali",
"Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome. – Booker T. Washington",
"The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh",
"Do not follow where the path may lead. Go instead where there is no path and leave a trail. – Ralph Waldo Emerson",
"Everything has beauty, but not everyone can see. – Confucius",
"Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson",
"The journey of a thousand miles begins with one step. – Lao Tzu",
"Be not afraid of life. Believe that life is worth living, and your belief will help create the fact. – William James",
"The greatest glory in living lies not in never falling, but in rising every time we fall. – Nelson Mandela",
"Life is either a daring adventure or nothing at all. – Helen Keller",
"In three words I can sum up everything I've learned about life: it goes on. – Robert Frost",
"The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
"Do not go where the path may lead, go instead where there is no path and leave a trail. – Ralph Waldo Emerson",
"The only way to do great work is to love what you do. – Steve Jobs",
"Everything you’ve ever wanted is on the other side of fear. – George Addair",
"Life is what happens when you’re busy making other plans. – John Lennon",
"You must be the change you wish to see in the world. – Mahatma Gandhi",
"Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
"The best way to predict your future is to create it. – Peter Drucker",
"Do not wait to strike till the iron is hot, but make it hot by striking. – William Butler Yeats",
"The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
"Success is not in what you have, but who you are. – Bo Bennett",
"To be the best, you must be able to handle the worst. – Wilson Kanadi",
"Believe you can and you're halfway there. – Theodore Roosevelt",
"You only live once, but if you do it right, once is enough. – Mae West",
"The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
"The only impossible journey is the one you never begin. – Tony Robbins",
"Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
"You do not find the happy life. You make it. – Camilla E. Kimball",
"Be yourself; everyone else is already taken. – Oscar Wilde",
"Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome. – Booker T. Washington",
"Everything you can imagine is real. – Pablo Picasso",
"The best revenge is massive success. – Frank Sinatra",
"Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
"Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
"Life isn’t about waiting for the storm to pass; it’s about learning how to dance in the rain. – Vivian Greene",
"Do not wait to strike till the iron is hot, but make it hot by striking. – William Butler Yeats",
"The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
"Everything has beauty, but not everyone can see. – Confucius",
"The journey of a thousand miles begins with one step. – Lao Tzu",
"Be not afraid of life. Believe that life is worth living, and your belief will help create the fact. – William James",
"The greatest glory in living lies not in never falling, but in rising every time we fall. – Nelson Mandela",
"Life is either a daring adventure or nothing at all. – Helen Keller",
"In three words I can sum up everything I've learned about life: it goes on. – Robert Frost",
"Opportunities don't happen. You create them. – Chris Grosser",
"Don’t be afraid to give up the good to go for the great. – John D. Rockefeller",
"Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
"Your time is limited, don't waste it living someone else's life. – Steve Jobs",
"Don't count the days, make the days count. – Muhammad Ali",
"Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome. – Booker T. Washington",
"The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh",
"Do not follow where the path may lead. Go instead where there is no path and leave a trail. – Ralph Waldo Emerson",
"Everything has beauty, but not everyone can see. – Confucius",
"Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson",
"The journey of a thousand miles begins with one step. – Lao Tzu",
"Be not afraid of life. Believe that life is worth living, and your belief will help create the fact. – William James"
];
function generateQuote() {
    var randomIndex = Math.floor(Math.random() * quotes.length);
    document.getElementById('quote').textContent = quotes[randomIndex];
}
